server:
  port: 8000

zuul:
  routes:
    auth:
      url: http://128.199.118.150:8001/api/auth
      path: /api/auth/**
    user:
      url: http://128.199.118.150:8001/api/user
      path: /api/user/**
    revenue:
      url: http://128.199.118.150:8002/api/statistic
      path: /api/statistic/**
    store:
      url: http://128.199.118.150:8002/api/store
      path: /api/store/**
    product:
      url: http://128.199.118.150:8002/api/product
      path: /api/product/**
    supplier:
      url: http://128.199.118.150:8002/api/supplier
      path: /api/supplier/**
    dispute:
      url: http://128.199.118.150:8002/api/dispute
      path: /api/dispute/**
    facebook:
      url: http://128.199.118.150:8002/api/facebook
      path: /api/facebook/**
    config:
      url: http://128.199.118.150:8002/api/config
      path: /api/config/**