server:
  port: 8000

zuul:
  routes:
    auth:
      url: http://localhost:8001/api/auth
      path: /api/auth/**
    user:
      url: http://localhost:8001/api/user
      path: /api/user/**
    revenue:
      url: http://localhost:8002/api/revenue
      path: /api/revenue/**
    fee:
      url: http://localhost:8002/api/fee
      path: /api/fee/**