server:
  port: 8000

zuul:
  routes:
    auth:
      url: http://localhost:8001/api/auth
      path: /api/auth/**
    user:
      url: http://localhost:8001/api/user
      path: /api/user/**
    business:
      url: http://localhost:8002/api/business
      path: /api/business/**