server:
  port: 8000

zuul:
  routes:
    auth:
      url: http://localhost:8001/api/auth
      path: /api/auth/**
    user:
      url: http://localhost:8001/api/user
      path: /api/user/**
    revenue:
      url: http://localhost:8002/api/statistic
      path: /api/statistic/**
    store:
      url: http://localhost:8002/api/store
      path: /api/store/**
    product:
      url: http://localhost:8002/api/product
      path: /api/product/**
    product-type:
      url: http://localhost:8002/api/product-type
      path: /api/product-type/**
    supplier:
      url: http://localhost:8002/api/supplier
      path: /api/supplier/**