server:
  port: 8000

zuul:
  routes:
    #Auth service
    auth:
      url: http://127.0.0.1:8001/api/auth
      path: /api/auth/**
    user:
      url: http://127.0.0.1:8001/api/user
      path: /api/user/**
    #Business service
    revenue:
      url: http://127.0.0.1:8002/api/statistic
      path: /api/statistic/**
    store:
      url: http://127.0.0.1:8002/api/store
      path: /api/store/**
    product:
      url: http://127.0.0.1:8002/api/product
      path: /api/product/**
    supplier:
      url: http://127.0.0.1:8002/api/supplier
      path: /api/supplier/**
    dispute:
      url: http://127.0.0.1:8002/api/dispute
      path: /api/dispute/**
    facebook:
      url: http://127.0.0.1:8002/api/facebook
      path: /api/facebook/**
    config:
      url: http://127.0.0.1:8002/api/config
      path: /api/config/**
    #Catalog service
    catalog:
      url: http://127.0.0.1:8003/api/catalog
      path: /api/catalog/**
    #File service
    file:
      url: http://127.0.0.1:8004/api/file
      path: /api/file/**