server:
  port: 8001

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/printway_account
    username: root
    password: root@123


  mail:
    host: smtp.gmail.com
    port: 587
    username: aptech.campaign@gmail.com
    password: 12004917
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true